name: ghsci
channels:
  - conda-forge
dependencies:
  - python
  - osmnx=2.0.* # OpenStreetMap network retrieval and analysis
  - gdal # GDAL and OGR libraries
  - libgdal-pg # PostgreSQL GDAL extension
  - pandas=2.1.* # pandas > 2.2 requires transition to Apache Arrow postgreSQL driver
  - nicegui=2.9.1 # web app framework
  - fpdf2=2.8.* # pdf templating
  - sqlalchemy=1.4.* # SQL connectivity with PostgreSQL
  - fonttools=4.55.*
  - jupyterlab=4.3.* # code notebooks / web interface
  - tqdm=4.*, >=4.66.3 # progress bar
  - openpyxl # Excel file reading
  - babel # language localization
  - cartopy # map plotting
  - contextily # basemaps and map styling
  - ipywidgets # for jupyter lab progress bar
  - geoalchemy2 # Geometry datatype extension for SQL Alchemy
  - pandana # network analysis using Pandas
  - rasterio # raster data reading
  - pygeometa # metadata templating tools
  - psycopg2 # PostgreSQL connection
  - pyyaml # YAML parsing
  - yamllint # YAML linting
  - uharfbuzz # text shaping for font rendering
  - urllib3>=2.2.3 # HTTP request handling (docker scout patch)
  - certifi>=2023.7.22 # SSL certificate verification (docker scout patch)
  - pip
  - pip: # python package installer
    - gtfs-lite # GTFS data reading
