name: ghsci
channels:
  - conda-forge
dependencies:
  - python=3.9.*
  - osmnx=1.2.3
  - fpdf2=2.6.*
  - openpyxl
  - babel
  - cartopy
  - contextily
  - geoalchemy2
  - pandana
  - psycopg2
  - pyyaml
  - rasterio
  - sphinx
  - sphinxcontrib-bibtex<2.0.0
  - sphinx_rtd_theme
  - urbanaccess
  - tqdm
