name: ghsci
channels:
  - conda-forge
dependencies:
  - python=3.10.*
  - osmnx=1.3.*
  - fpdf2=2.6.*
  - sqlalchemy>=1.4,<2.0
  - cryptography>=39.0.1,<40.0.0
  - openpyxl
  - babel
  - cartopy
  - contextily
  - jupyter
  - geoalchemy2
  - pandana
  - psycopg2
  - pyyaml
  - rasterio
  - urbanaccess
  - tqdm
  - pygeometa
